name: Deploy to Server

on:
    push:
        branches: [ys]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

             # SCP로 서버로 전송
            - name: SCP transfer
              uses: appleboy/scp-action@master
              with:
                  username: ${{ secrets.SERVER_USER }}
                  host: ${{ secrets.SERVER_IP }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  source: .
                  target: /ai
                
    
